var host = window.location.host;
if ( host.toLowerCase().includes("youtube") ) {

  var script = document.createElement("script");
  var code = `
	var simple_words=[
	        {"about":"sur","after":"après","again":"encore","air":"air","all":"tout","along":"le long de","also":"également","another":"un autre","any":"tout","are":"sont","around":"autour","as":"comme","at":"à","away":"une façon","back":"retour","be":"être","because":"parce que","been":"été","before":"avant","below":"au dessous de","between":"entre","both":"tous les deux","but":"mais","by":"par","came":"venu","can":"pouvez","come":"viens","could":"pourrait","day":"journée","did":"fait","different":"différent","do":"faire","does":"Est-ce que","don't":"ne pas","down":"vers le bas","each":"chaque","end":"fin","even":"même","every":"chaque","few":"peu","find":"trouver","first":"premier","for":"pour","found":"a trouvé","from":"de","get":"obtenir","give":"donner","go":"aller","good":"bien","great":"génial","had":"eu","has":"a","have":"avoir","he":"il","help":"Aidez-moi","her":"sa","here":"ici","him":"lui","his":"le sien","home":"maison","house":"maison","how":"Comment","if":"si","in":"dans","into":"dans","is":"est","it":"il","its":"ses","just":"juste","know":"savoir","large":"grand","last":"dernier","left":"la gauche","like":"comme","line":"ligne","little":"peu","long":"longue","look":"Regardez","made":"fabriqué","make":"faire","man":"homme","many":"beaucoup","may":"peut","me":"moi","men":"Hommes","might":"pourrait","more":"plus","most":"plus","Mr.":"M.","must":"doit","my":"mon","name":"prénom","never":"jamais","new":"Nouveau","next":"suivant","no":"non","not":"ne pas","now":"à présent","number":"nombre","of":"de","off":"de","old":"vieux","on":"sur","one":"un","only":"seulement","or":"ou","other":"autre","our":"notre","out":"en dehors","over":"plus de","own":"posséder","part":"partie","people":"personnes","place":"endroit","put":"mettre","read":"lis","right":"droite","said":"m'a dit","same":"même","saw":"vu","say":"dire","see":"voir","she":"elle","should":"devrait","show":"spectacle","small":"petit","so":"alors","some":"certains","something":"quelque chose","sound":"du son","still":"encore","such":"tel","take":"prendre","tell":"dire","than":"que","that":"cette","the":"la","them":"leur","then":"puis","there":"Là","these":"celles-ci","they":"ils","thing":"chose","think":"pense","this":"ce","those":"ceux","thought":"pensée","three":"Trois","through":"à travers","time":"temps","to":"à","together":"ensemble","too":"aussi","two":"deux","under":"sous","up":"en haut","use":"utilisation","very":"très","want":"vouloir","water":"eau","way":"façon","well":"bien","went":"est allé","were":"étaient","what":"quoi","when":"quand","where":"où","which":"lequel","while":"tandis que","who":"qui","why":"pourquoi","with":"avec","word":"mot","work":"travail","world":"monde","write":"écrire","year":"année","your":"votre","was":"était"},
	        {"able":"capable","above":"au dessus de","across":"à travers","add":"ajouter","against":"contre","ago":"depuis","almost":"presque","among":"parmi","animal":"animal","answer":"réponse","became":"est devenu","become":"devenir","began":"a commencé","behind":"derrière","being":"étant","better":"meilleur","black":"noir","best":"meilleur","body":"corps","book":"livre","boy":"garçon","brought":"apporté","call":"appel","cannot":"ne peux pas","car":"voiture","certain":"certain","change":"changement","children":"les enfants","city":"ville","close":"fermer","cold":"du froid","country":"pays","course":"cours","cut":"Couper","didn't":"n'a pas","dog":"chien","done":"terminé","door":"porte","draw":"dessiner","during":"pendant","early":"de bonne heure","earth":"Terre","eat":"manger","enough":"assez","ever":"déjà","example":"Exemple","eye":"œil","face":"visage","family":"famille","far":"loin","father":"père","feel":"ressentir","feet":"pieds","fire":"Feu","fish":"poisson","five":"cinq","food":"aliments","form":"forme","four":"quatre","front":"de face","gave":"a donné","given":"donné","got":"eu","green":"vert","ground":"sol","group":"groupe","grow":"croître","half":"moitié","hand":"main","hard":"difficile","heard":"entendu","high":"haute","himself":"lui-même","however":"toutefois","I'll":"Je vais","I'm":"je suis","idea":"idée","important":"important","inside":"à l'intérieur","John":"John","keep":"garder","kind":"gentil","knew":"a connu","known":"connu","land":"terre","later":"plus tard","learn":"apprendre","let":"laisser","letter":"lettre","life":"la vie","light":"lumière","live":"vivre","living":"vivant","making":"fabrication","mean":"signifier","means":"veux dire","money":"argent","morning":"Matin","mother":"mère","move":"bouge toi","Mrs.":"Mme.","near":"près","night":"nuit","nothing":"rien","once":"une fois que","open":"ouvrir","order":"ordre","page":"page","paper":"papier","parts":"les pièces","perhaps":"peut-être","picture":"image","play":"jouer","point":"point","ready":"prêt","red":"rouge","remember":"rappelles toi","rest":"du repos","room":"pièce","run":"courir","school":"école","sea":"mer","second":"seconde","seen":"vu","sentence":"phrase","several":"nombreuses","short":"court","shown":"montré","since":"puisque","six":"six","slide":"faire glisser","sometime":"un jour","soon":"bientôt","space":"espace","States":"États","story":"récit","sun":"Soleil","sure":"sûr","table":"table","though":"bien que","today":"aujourd'hui","told":"Raconté","took":"a pris","top":"Haut","toward":"vers","tree":"arbre","try":"essayer","turn":"tour","United":"Uni","until":"jusqu'à ce que","upon":"sur","using":"en utilisant","usually":"d'habitude","white":"blanc","whole":"entier","wind":"vent","without":"sans pour autant","yes":"Oui","yet":"encore","young":"Jeune","already":"déjà"},
	        {"although":"bien que","am":"suis","America":"Amérique","anything":"n'importe quoi","area":"surface","ball":"ballon","beautiful":"belle","beginning":"début","Bill":"Facture","birds":"des oiseaux","blue":"bleu","boat":"bateau","bottom":"bas","box":"boîte","bring":"apporter","build":"construire","building":"bâtiment","built":"construit","can't":"ne peut pas","care":"se soucier","carefully":"soigneusement","carried":"porté","carry":"porter","center":"centre","check":"vérifier","class":"classe","coming":"venant","common":"commun","complete":"Achevée","dark":"foncé","deep":"Profond","distance":"distance","doing":"Faire","dry":"sec","easy":"facile","either":"non plus","else":"autre","everyone":"toutes les personnes","everything":"tout","fact":"fait","fall":"tomber","fast":"vite","felt":"se sentait","field":"champ","finally":"enfin","fine":"bien","floor":"sol","follow":"suivre","foot":"pied","friend":"ami","full":"plein","game":"Jeu","getting":"obtenir","girl":"fille","glass":"verre","goes":"va","gold":"or","gone":"disparu","happened":"arrivé","having":"ayant","heart":"cœur","heavy":"lourd","held":"tenue","hold":"tenir","horse":"cheval","hot":"chaud","hour":"heure","hundred":"cent","ice":"la glace","Indian":"Indien","instead":"au lieu","itself":"lui-même","job":"emploi","kept":"conservé","language":"la langue","lay":"allonger","least":"moins","leave":"laisser","let's":"allons","list":"liste","longer":"plus long","low":"faible","main":"principale","map":"carte","matter":"matière","mind":"esprit","Miss":"Mademoiselle","moon":"lune","mountain":"Montagne","moving":"en mouvement","music":"la musique","needed":"nécessaire","notice":"remarquer","outside":"à l'extérieur","past":"passé","pattern":"modèle","person":"la personne","piece":"pièce","plant":"plante","poor":"pauvre","possible":"possible","power":"Puissance","probably":"Probablement","problem":"problème","question":"question","quickly":"rapidement","quite":"assez","rain":"pluie","ran":"a couru","real":"réal","river":"rivière","road":"route","rock":"Roche","round":"rond","sat":"Sam","scientist":"scientifique","shall":"doit","ship":"navire","simple":"simple","size":"Taille","sky":"ciel","slowly":"lentement","snow":"neige","someone":"Quelqu'un","special":"spécial","stand":"supporter","start":"début","state":"Etat","stay":"rester","stood":"debout","stop":"Arrêtez","stopped":"arrêté","strong":"fort","suddenly":"soudainement","summer":"été","surface":"surface","system":"système","taken":"pris","talk":"parler","tall":"grand","ten":"Dix","that's":"c'est","themselves":"se","third":"troisième","tiny":"minuscule","town":"ville","tried":"a tenté","voice":"voix","walk":"marche","warm":"chaud","watch":"regarder","weather":"Météo","whether":"qu'il s'agisse","wide":"large","wild":"sauvage","winter":"hiver","within":"dans","writing":"l'écriture","written":"écrit"},
	        {"age":"âge","ask":"demander","baby":"bébé","base":"base","beside":"à côté de","bright":"brillant","business":"affaires","buy":"acheter","case":"Cas","catch":"capture","caught":"pris","child":"enfant","choose":"choisir","circle":"cercle","clear":"clair","color":"Couleur","copy":"copie","correct":"correct","couldn't":"ne pouvait pas","difference":"différence","direction":"direction","dried":"séché","easily":"facilement","edge":"bord","egg":"Oeuf","eight":"huit","energy":"énergie","England":"Angleterre","especially":"notamment","Europe":"L'Europe","exactly":"exactement","except":"sauf","explain":"Explique","famous":"célèbre","farm":"ferme","fell":"est tombée","figure":"figure","flat":"appartement","fly":"voler","forest":"forêt","free":"libre","French":"français","fun":"amusement","George":"George","government":"gouvernement","grass":"herbe","grew":"a grandi","hair":"cheveux","happy":"heureux","he's":"il est","heat":"chaleur","history":"l'histoire","human":"Humain","I've":"J'ai","inch":"pouce","information":"information","iron":"le fer","Jim":"Jim","Joe":"Joe","King":"Roi","larger":"plus grand","late":"en retard","leg":"jambe","length":"longueur","listen":"écoute","lost":"perdu","lot":"lot","lower":"inférieur","machine":"machine","mark":"marque","maybe":"peut être","measure":"mesure","meet":"rencontrer","middle":"milieu","milk":"Lait","minute":"minute","modern":"moderne","moment":"moment","month":"mois","mouth":"bouche","natural":"Naturel","nearly":"presque","necessary":"nécessaire","New York":"New York","north":"Nord","object":"objet","ocean":"océan","oil":"pétrole","pay":"Payer","per":"par","plan":"plan","plane":"avion","present":"présent","product":"produit","rather":"plutôt","reach":"atteindre","reason":"raison","record":"record","running":"fonctionnement","seems":"semble","sent":"envoyé","seven":"Sept","shape":"forme","sides":"côtés","single":"unique","skin":"peau","sleep":"dormir","smaller":"plus petite","soft":"doux","soil":"sol","south":"Sud","speak":"parler","speed":"la vitesse","spring":"printemps","square":"carré","star":"étoile","step":"étape","store":"le magasin","straight":"tout droit","strange":"étrange","street":"rue","subject":"assujettir","suppose":"supposer","teacher":"prof","thousand":"mille","thus":"Ainsi","Tom":"À M","travel":"Voyage","trip":"voyage","trouble":"difficulté","unit":"unité","village":"village","wall":"mur","war":"guerre","wasn't":"n'était pas","week":"la semaine","whose":"dont","window":"la fenêtre","wish":"souhait","women":"femmes","won't":"habitude","wood":"bois","wrote":"a écrit","yellow":"jaune","you're":"tu es","yourself":"toi même"},
	        {"action":"action","addition":"une addition","afraid":"peur","afternoon":"après midi","ahead":"devant","amount":"montant","ancient":"ancien","anyone":"n'importe qui","arm":"bras","bad":"mal","bear":"ours","beyond":"au-delà","bit":"bit","blood":"du sang","board":"planche","Bob":"Bob","born":"née","break":"Pause","British":"Britanique","broken":"cassé","brother":"frère","brown":"marron","busy":"occupé","capital":"Capitale","cat":"chat","cattle":"bétail","cause":"cause","century":"siècle","chance":"chance","clean":"nettoyer","clothes":"vêtements","coast":"côte","control":"contrôle","cool":"cool","corn":"blé","corner":"coin","cover":"couverture","cross":"traverser","Dan":"Dan","dead":"morte","deal":"traiter","death":"mort","decide":"décider","difficult":"difficile","doesn't":"ne pas","drive":"conduire","engine":"moteur","evening":"soir","farmer":"agriculteur","faster":"plus rapide","fight":"bats toi","fill":"remplir","finger":"doigt","force":"Obliger","forward":"vers l'avant","France":"France","fresh":"Frais","garden":"jardin","general":"général","glad":"content de","greater":"plus grand","greatest":"le plus grand","guess":"deviner","happen":"se produire","Henry":"Henri","higher":"plus haute","hit":"frappé","hole":"trou","hope":"espérer","huge":"énorme","interest":"intérêt","island":"île","isn't":"n'est pas","jack":"jack","lady":"Dame","largest":"le plus grand","lead":"conduire","led":"LED","level":"niveau","love":"amour","Mary":"Marie","material":"Matériel","meant":"signifiait","meat":"moi à","method":"méthode","missing":"manquant","needs":"Besoins","nor":"ni","nose":"nez","note":"Remarque","opposite":"contraire","pair":"paire","party":"fête","pass":"passer","period":"période","please":"S'il vous plaît","position":"position","pound":"livre","practice":"entraine toi","pretty":"joli","produce":"produire","pull":"tirez","quiet":"silencieux","race":"course","radio":"radio","region":"Région","result":"résultat","return":"revenir","rich":"riches","ride":"balade","ring":"bague","rule":"règle","sand":"le sable","science":"science","section":"section","seed":"la graine","send":"envoyer","sense":"sens","sets":"ensembles","sharp":"tranchant","sight":"vue","sign":"signe","silver":"argent","similar":"similaire","sit":"asseoir","son":"fils","song":"chanson","spent":"dépensé","spread":"propager","stick":"bâton","stone":"pierre","tail":"queue","team":"équipe","teeth":"les dents","temperature":"Température","test":"tester","there's":"il y a","therefore":"donc","thick":"épais","thin":"mince","train":"train","various":"divers","wait":"attendre","Washington":"Washington","wave":"vague","we'll":"bien","weight":"poids","west":"Ouest","wife":"femme","wouldn't":"ne serait pas","wrong":"faux","you'll":"tu vas"},
	        {"according":"selon","act":"acte","actually":"réellement","Africa":"Afrique","alike":"ressemblent","apart":"une part","ate":"a mangé","attention":"attention","bank":"banque","basic":"de base","beat":"battre","blow":"coup","bone":"OS","bread":"pain","careful":"prudent","chair":"chaise","chief":"chef","Christmas":"Noël","church":"église","cloth":"tissu","cloud":"nuage","column":"colonne","compare":"comparer","contain":"contenir","continued":"a continué","cost":"Coût","cotton":"coton","count":"compter","dance":"Danse","describe":"décrire","desert":"désert","dinner":"dîner","doctor":"médecin","dollar":"dollar","drop":"laissez tomber","dropped":"chuté","ear":"oreille","east":"est","electric":"électrique","element":"élément","enjoy":"prendre plaisir","equal":"égal","exercise":"exercice","experiment":"expérience","familiar":"familier","farther":"plus loin","fear":"peur","forth":"en avant","gas":"gaz","giving":"donnant","gray":"gris","grown":"grandi","hardly":"à peine","hat":"chapeau","hill":"colline","hurt":"blesser","I'd":"J'aurais","imagine":"imaginer","include":"comprendre","indeed":"effectivement","Johnny":"Johnny","joined":"rejoint","key":"clé","kitchen":"cuisine","knowledge":"connaissance","law":"loi","lie":"mensonge","major":"Majeur","met":"rencontré","metal":"métal","movement":"mouvement","nation":"nation","nature":"la nature","nine":"neuf","none":"aucun","office":"Bureau","older":"plus âgée","onto":"sur","original":"original","paragraph":"paragraphe","parent":"parent","particular":"particulier","path":"chemin","Paul":"Paul","Peter":"Peter","pick":"choisir","president":"Président","pressure":"pression","process":"processus","public":"Publique","quick":"rapide","report":"rapport","rope":"corde","rose":"Rose","row":"rangée","safe":"sûr","salt":"sel","Sam":"Sam","scale":"échelle","sell":"vendre","separate":"séparé","sheep":"mouton","shoe":"chaussure","shore":"rive","simply":"simplement","sing":"chanter","sister":"sœur","sitting":"séance","sold":"vendu","soldier":"soldat","solve":"résoudre","speech":"discours","spend":"dépenser","steel":"acier","string":"chaîne","student":"étudiant","studied":"étudié","sugar":"sucre","television":"télévision","term":"terme","throughout":"tout au long de","tired":"fatigué","total":"total","touch":"toucher","trade":"Commerce","truck":"un camion","twice":"deux fois","type":"type","uncle":"oncle","unless":"sauf si","useful":"utile","value":"valeur","verb":"verbe","visit":"visite","wear":"porter","what's":"c'est quoi","wheel":"roue","William":"William","wing":"aile","wire":"câble","won":"a gagné","wonder":"merveille","worker":"ouvrier","yard":"Cour"},
	        {"alive":"vivant","angry":"fâché","army":"armée","average":"moyenne","bag":"sac","band":"B: et","Billy":"Gamelle","branch":"branche","breakfast":"petit déjeuner","breath":"souffle","broke":"cassé","bus":"autobus","cabin":"cabine","California":"Californie","camp":"camp","captain":"capitaine","cell":"cellule","cent":"cent","certainly":"certainement","changing":"en changeant","closer":"plus proche","coal":"charbon","coat":"manteau","community":"communauté","company":"entreprise","completely":"complètement","compound":"composé","condition":"état","consider":"considérer","correctly":"correctement","crop":"surgir","crowd":"foule","current":"actuel","danger":"danger","dear":"cher","degree":"diplôme","develop":"développer","die":"mourir","directly":"directement","discover":"découvrir","divide":"diviser","double":"double","Dr.":"Dr.","dress":"robe","drink":"boisson","drove":"a conduit","dust":"poussière","easier":"Plus facile","effect":"effet","electricity":"électricité","empty":"vide","entire":"tout","everybody":"Tout le monde","exciting":"passionnant","expect":"attendre","experience":"expérience","express":"Express","fair":"juste","feed":"alimentation","final":"final","finish":"terminer","flew":"a volé","fruit":"fruit","further":"plus loin","future":"futur","Greek":"grec","guide":"guider","gun":"pistolet","herself":"se","hungry":"faim","instrument":"instrument","Jane":"Jeanne","join":"joindre","jump":"saut","laid":"posé","liquid":"liquide","loud":"bruyant","market":"marché","member":"membre","Mexico":"Mexique","Mike":"Mike","mine":"mien","motion":"mouvement","myself":"moi même","neck":"cou","news":"nouvelles","nice":"agréable","noise":"bruit","noun":"nom","oxygen":"oxygène","paid":"payé","phrase":"phrase","plain":"plaine","poem":"poème","population":"population","proper":"correct","proud":"fier","provide":"fournir","purpose":"objectif","putting":"en mettant","quietly":"tranquillement","raise":"élever","range":"intervalle","rate":"taux","regular":"ordinaire","related":"en relation","replied":"a répondu","represent":"représenter","rise":"monter","scientific":"scientifique","season":"saison","seat":"siège","share":"partager","shot":"coup","shoulder":"épaule","slow":"lent","smile":"sourire","solid":"solide","solution":"Solution","sort":"Trier","southern":"du sud","stage":"étape","statement":"déclaration","station":"station","steam":"vapeur","stream":"courant","strength":"force","supply":"la fourniture","surprise":"surprise","symbol":"symbole","till":"jusqu'à","tomorrow":"demain","tube":"tube","twelve":"Douze","twenty":"vingt","usual":"habituel","valley":"vallée","variety":"variété","vowel":"voyelle","we're":"étaient","wet":"humide","wooden":"en bois","worth":"vaut"},
	        {"airplane":"avion","angle":"angle","Ann":"Ann","apple":"Pomme","art":"art","Atlantic":"atlantique","atmosphere":"atmosphère","bar":"bar","barn":"Grange","baseball":"base-ball","beauty":"beauté","believed":"a cru","bell":"cloche","belong":"appartenir","beneath":"sous","bigger":"plus gros","bottle":"bouteille","bowl":"bol","broad":"vaste","chapter":"chapitre","chart":"graphique","Chinese":"chinois","clearly":"clairement","climate":"climat","clock":"l'horloge","closely":"étroitement","clothing":"Vêtements","coffee":"café","cow":"vache","cry":"cri","Dad":"Papa","dangerous":"dangereux","deer":"cerf","desk":"bureau","detail":"détail","development":"développement","drew":"a dessiné","driver":"chauffeur","event":"un événement","everywhere":"partout","fat":"graisse","favorite":"préféré","fence":"clôture","fifty":"cinquante","flight":"vol","flow":"couler","flower":"fleur","forget":"oublier","fourth":"Quatrième","friendly":"amical","generally":"généralement","German":"allemand","Germany":"Allemagne","giant":"géant","golden":"d'or","grain":"grain","handle":"manipuler","height":"la taille","hung":"accroché","hurry":"se dépêcher","immediately":"immédiatement","industry":"industrie","instance":"exemple","Italy":"Italie","James":"James","knife":"couteau","lake":"Lac","Latin":"Latin","leader":"chef","leaving":"en quittant","likely":"probable","lunch":"le déjeuner","mass":"Masse","master":"maîtriser","mile":"mile","mix":"mélanger","model":"modèle","mud":"boue","muscle":"muscle","nearby":"proche","nearest":"la plus proche","nest":"nid","newspaper":"journal","nobody":"personne","observe":"observer","Pacific":"Pacifique","peace":"paix","plate":"assiette","plenty":"beaucoup","popular":"populaire","powerful":"puissant","push":"pousser","railroad":"chemin de fer","rapidly":"rapidement","root":"racine","rubber":"caoutchouc","sad":"triste","sail":"voile","save":"enregistrer","score":"But","seeing":"voyant","serious":"sérieux","service":"un service","sheet":"drap","shop":"boutique","silent":"silencieux","smell":"odeur","smoke":"fumée","smooth":"lisse","source":"la source","spell":"épeler","storm":"orage","structure":"structure","supper":"souper","support":"soutien","sweet":"sucré","swim":"nager","telephone":"Téléphone","Texas":"Texas","threw":"jeta","throw":"jeter","tone":"Ton","tool":"outil","track":"Piste","trail":"Piste","understanding":"compréhension","upper":"plus haut","view":"vue","wagon":"wagon","western":"occidental","whatever":"peu importe","wheat":"blé","whenever":"n'importe quand","whom":"qui","win":"gagner","wonderful":"merveilleux","wore":"portait"},
	        {"ability":"aptitude","agree":"se mettre d'accord","ants":"fourmis","Asia":"Asie","asleep":"endormi","attack":"attaque","balance":"équilibre","bat":"chauve souris","battle":"bataille","Ben":"Ben","block":"bloc","bow":"arc","brain":"cerveau","brave":"courageux","bridge":"pont","cave":"la grotte","charge":"charge","chemical":"chimique","China":"Chine","clay":"argile","climb":"montée","composition":"composition","congress":"congrès","copper":"cuivre","crew":"équipage","cup":"tasse","daughter":"fille","design":"conception","determine":"déterminer","direct":"direct","discuss":"discuter","division":"division","drawn":"tiré","earlier":"plus tôt","eaten":"mangé","education":"éducation","enemy":"ennemi","enter":"entrer","equipment":"équipement","escape":"échapper","European":"européen","excited":"excité","expression":"expression","extra":"supplémentaire","factory":"usine","feathers":"plumes","fellow":"compagnon","fighting":"combat","fought":"combattu","Frank":"Franc","freedom":"liberté","funny":"marrant","fur":"fourrure","growth":"croissance","hall":"salle","he'd":"il aurait","health":"santé","highest":"plus haut","hunt":"chasse","including":"comprenant","increase":"augmenter","indicate":"indiquer","individual":"individuel","Japanese":"Japonais","kill":"tuer","laugh":"rire","library":"bibliothèque","lift":"ascenseur","lion":"Lion","local":"local","lose":"perdre","lovely":"charmant","lying":"mensonge","magic":"la magie","Mama":"Maman","manner":"manière","Mark":"marque","May":"Peut","mostly":"la plupart","national":"nationale","neighbor":"voisin","ordinary":"ordinaire","parallel":"parallèle","park":"parc","particularly":"particulièrement","pencil":"crayon","perfect":"parfait","planet":"planète","planned":"prévu","pleasant":"agréable","pocket":"poche","police":"police","political":"politique","post":"poster","potatoes":"patates","price":"prix","printed":"imprimé","program":"programme","property":"propriété","prove":"prouver","remain":"rester","riding":"équitation","roll":"rouleau","Roman":"romain","roof":"toit","rough":"rugueux","scene":"scène","search":"chercher","secret":"secret","series":"séries","serve":"servir","settlers":"les colons","shinning":"brillant","shut":"fermer","signal":"signal","Sir":"Monsieur","skill":"compétence","smallest":"le plus petit","social":"social","softly":"doucement","St.":"St.","struck":"frappé","studying":"en train d'étudier","success":"Succès","suit":"costume","sunlight":"lumière du soleil","swimming":"nager","taste":"goût","taught":"enseigné","thank":"remercier","they're":"ils sont","tip":"pointe","title":"Titre","tongue":"langue","valuable":"de valeur","vast":"vaste","vegetable":"légume","wash":"lavage","weak":"faible","you've":"vous avez"},
	        {"activity":"activité","Alaska":"Alaska","appearance":"apparence","aren't":"ne sont pas","article":"article","Aunt":"Tante","automobile":"voiture","avoid":"éviter","basket":"panier","birthday":"anniversaire","cage":"cage","cake":"gâteau","Canada":"Canada","central":"central","character":"personnage","Charles":"Charles","chicken":"poulet","chosen":"choisi","club":"club","cook":"cuisinier","court":"tribunal","cream":"crème","cutting":"Coupe","daily":"du quotidien","darkness":"ténèbres","diagram":"diagramme","Dick":"Queue","disappear":"disparaître","doubt":"doute","dozen":"douzaine","dream":"rêver","driving":"conduite","effort":"effort","establish":"établir","exact":"exact","excitement":"excitation","fifteen":"quinze","flag":"drapeau","flies":"mouches","football":"Football","foreign":"étranger","frame":"Cadre","frequently":"souvent","frighten":"effrayer","function":"une fonction","gate":"porte","gently":"doucement","gradually":"progressivement","hadn't":"n'avait pas","harder":"Plus fort","hide":"cacher","hurried":"pressé","identity":"identité","importance":"importance","impossible":"impossible","India":"Inde","invented":"a inventé","Italian":"italien","jar":"pot","journey":"périple","joy":"joie","lesson":"leçon","Lincoln":"Lincoln","lips":"lèvres","log":"bûche","London":"Londres","loose":"en vrac","massage":"massage","minerals":"minéraux","outer":"extérieur","paint":"peindre","Papa":"Papa","Paris":"Paris","particles":"des particules","personal":"personnel","physical":"physique","pie":"tarte","pipe":"tuyau","pole":"pôle","pond":"étang","progress":"le progrès","quarter":"trimestre","rays":"des rayons","recent":"récent","recognize":"reconnaître","replace":"remplacer","rhythm":"rythme","Richard":"Richard","Robert":"Robert","rod":"barre","ruler":"règle","safety":"sécurité","Sally":"Sortie","sang":"a chanté","setting":"réglage","shells":"coquilles","sick":"malade","situation":"situation","slightly":"légèrement","Spain":"Espagne","spirit":"esprit","steady":"stable","stepped":"a marché","strike":"la grève","successful":"réussi","sudden":"soudain","sum":"somme","terrible":"terrible","tie":"attacher","traffic":"trafic","unusual":"inhabituel","volume":"le volume","whale":"baleine","wise":"sage","yesterday":"hier"},
	        {"account":"Compte","allow":"permettre","anywhere":"nulle part","attached":"attaché","audience":"public","available":"disponible","balloon":"ballon","bare":"nu","bark":"écorce","begun":"commencé","bent":"courbé","biggest":"le plus gros","bill":"facture","blank":"blanc","blew":"soufflé","breathing":"respiration","butter":"beurre","cap":"casquette","carbon":"carbone","card":"carte","chain":"chaîne","cheese":"fromage","chest":"poitrine","Chicago":"Chicago","choice":"choix","circus":"cirque","citizen":"citoyen","classroom":"salle de cours","college":"Université","consist":"consister","continent":"continent","conversation":"conversation","courage":"courage","cowboy":"cow-boy","creature":"créature","date":"rendez-vous amoureux","depend":"dépendre","differ":"différer","discovery":"Découverte","disease":"maladie","duck":"canard","due":"dû","Dutch":"néerlandais","entirely":"entièrement","environment":"environnement","exclaimed":"s'écria","factor":"facteur","fog":"brouillard","forgot":"oublié","forgotten":"oublié","frozen":"congelé","fuel":"carburant","furniture":"meubles","gather":"recueillir","gentle":"doux","globe":"globe","grandfather":"grand-père","greatly":"très","haven't":"n'ont pas","helpful":"utile","hidden":"caché","honor":"honneur","husband":"mari","involved":"impliqué","Japan":"Japon","jet":"jet","Jimmy":"Jimmy","layers":"couches","leaf":"feuille","leather":"cuir","load":"charge","lonely":"solitaire","Louis":"Louis","March":"Mars","meal":"repas","medicine":"médicament","merely":"seulement","mice":"des souris","molecular":"moléculaire","musical":"musical","native":"originaire de","Negro":"nègre","noon":"le midi","occur":"se produire","orange":"Orange","ought":"devrait","pack":"pack","partly":"partiellement","pet":"animal de compagnie","pine":"pin","pink":"rose","pitch":"pas","pool":"bassin","prepare":"préparer","press":"presse","prevent":"prévenir","pure":"pur","queen":"reine","rabbit":"lapin","ranch":"ranch","realize":"prendre conscience de","receive":"recevoir","recently":"récemment","rice":"riz","rising":"en hausse","rocket":"fusée","Saturday":"samedi","saved":"enregistré","shade":"ombre","shadow":"ombre","shirt":"chemise","shoot":"tirer","shorter":"plus court","silence":"silence","slipped":"glissé","Smith":"Forgeron","snake":"serpent","somewhere":"quelque part","spoken":"parlé","standard":"la norme","straw":"paille","strip":"bande","substance":"substance","suggest":"suggérer","Sunday":"dimanche","teach":"apprendre","tears":"larmes","thirty":"30","Thomas":"Thomas","thread":"fil","throat":"gorge","tight":"serré","tin":"étain","triangle":"Triangle","truth":"vérité","union":"syndicat","warn":"prévenir","whispered":"chuchoté","wool":"la laine","you'd":"vous auriez"},
	        {"aid":"aide","aloud":"à haute voix","Andy":"Andy","anyway":"en tous cas","arrow":"flèche","aside":"de côté","atomic":"atomique","author":"auteur","basis":"base","bean":"haricot","becoming":"devenir","Betsy":"Betsy","bicycle":"vélo","blanket":"couverture","brush":"brosse","buffalo":"buffle","burn":"brûler","burst":"éclater","bush":"buisson","Carlos":"Carlos","collect":"collecte","colony":"colonie","combination":"combinaison","combine":"combiner","comfortable":"confortable","complex":"complexe","composed":"composé","concerned":"concerné","connected":"connecté","construction":"construction","couple":"couple","create":"créer","curious":"curieuse","dig":"creuser","dirt":"saleté","distant":"loin","dot":"point","Edward":"Edward","elephant":"l'éléphant","etc.":"etc.","evidence":"preuve","examine":"examiner","excellent":"excellent","failed":"échoué","fallen":"déchue","fastened":"attaché","feature":"fonctionnalité","fed":"nourris","gain":"Gain","graph":"graphique","hearing":"audition","highway":"Autoroute","improve":"améliorer","influence":"influence","July":"juillet","June":"juin","lack":"manquer de","lamp":"lampe","locate":"Localiser","luck":"la chance","mail":"courrier","married":"marié","mighty":"puissant","mirror":"miroir","Mississippi":"Mississippi","motor":"moteur","mouse":"Souris","needle":"aiguille","nodded":"acquiesça","numeral":"numéral","offer":"offre","oldest":"le plus vieux","operation":"opération","orbit":"orbite","organized":"organisé","outline":"contour","pain":"douleur","pan":"la poêle","pen":"stylo","piano":"piano","pictured":"sur la photo","pig":"porc","pile":"pile","planning":"Planification","pony":"poney","principal":"principal","production":"production","refer":"référer","religious":"religieux","repeat":"répéter","research":"recherche","respect":"le respect","review":"la revue","route":"route","silk":"soie","slept":"dormi","spite":"dépit","stretch":"étendue","stronger":"plus forte","stuck":"coincé","swing":"balançoire","task":"tâche","tax":"impôt","tea":"thé","tent":"tente","thee":"te","theory":"théorie","thrown":"jeté","tonight":"ce soir","topic":"sujet","tower":"la tour","transportation":"transport","trick":"tour","underline":"souligner","unknown":"inconnu","upward":"ascendant","Virginia":"Virginie","waste":"déchets","we've":"nous avons","wherever":"partout où","willing":"prêt","worry":"inquiéter","worse":"pire","youth":"jeunesse"},
	        {"accept":"Acceptez","accident":"accident","active":"actif","additional":"Additionnel","adjective":"adjectif","affect":"affecter","Alice":"Alice","alphabet":"alphabet","announced":"annoncé","anybody":"n'importe qui","April":"avril","arrange":"organiser","Australia":"Australie","aware":"conscient","badly":"mal","bee":"abeille","belt":"ceinture","bite":"mordre","blind":"aveugle","bound":"lié","castle":"Château","characteristic":"caractéristiques","Columbus":"Colomb","compass":"boussole","consonant":"consonne","curve":"courbe","definition":"définition","dish":"plat","Don":"Don","driven":"conduit","dug":"creusé","earn":"gagner","Eddy":"Tourbillon","eventually":"finalement","explore":"explorer","fairly":"équitablement","fewer":"moins","fifth":"cinquième","Florida":"Floride","gasoline":"de l'essence","gift":"cadeau","grade":"qualité","halfway":"à mi-chemin","hang":"pendre","he'll":"enfer","headed":"à tête","herd":"troupeau","hollow":"creux","income":"le revenu","industrial":"industriel","introduced":"introduit","Johnson":"Johnson","Jones":"Jones","judge":"juge","loss":"perte","lucky":"chanceux","machinery":"machinerie","mad":"furieux","magnet":"aimant","Mars":"Mars","military":"militaire","mistake":"erreur","mood":"ambiance","nails":"ongles","naturally":"naturellement","negative":"négatif","obtain":"obtenir","origin":"origine","owner":"propriétaire","passage":"passage","percent":"pour cent","perfectly":"à la perfection","pilot":"pilote","pleasure":"plaisir","plural":"pluriel","plus":"plus","poet":"poète","porch":"porche","pot":"pot","powder":"poudre","previous":"précédent","primitive":"primitif","principle":"principe","prize":"prix","purple":"violet","raw":"brut","reader":"lecteur","remove":"retirer","salmon":"Saumon","screen":"écran","seldom":"rarement","select":"sélectionner","society":"société","somebody":"quelqu'un","specific":"spécifique","spider":"araignée","sport":"sport","stairs":"escaliers","stared":"regardé","steep":"raide","stomach":"estomac","stove":"poêle","stranger":"étranger","struggle":"lutte","surrounded":"entouré","swam":"nagé","syllable":"syllabe","tank":"réservoir","tape":"ruban","thou":"tu","tightly":"fermement","Tim":"Tim","trace":"trace","tribe":"tribu","trunk":"tronc","TV":"la télé","universe":"univers","visitor":"visiteur","vote":"vote","weigh":"peser","Wilson":"Wilson","younger":"plus jeune","zero":"zéro"},
	        {"aboard":"une planche","accurate":"précis","actual":"réel","adventure":"aventure","apartment":"appartement","applied":"appliqué","appropriate":"approprié","arrive":"arrivée","atom":"atome","Bay":"baie","behavior":"comportement","bend":"pliez","bet":"pari","birth":"naissance","brass":"laiton","breathe":"respirer","brief":"bref","buried":"enterré","camera":"caméra","captured":"capturé","chamber":"chambre","command":"commander","crack":"fissure","Daniel":"Daniel","David":"David","dawn":"Aube","declared":"déclaré","diameter":"diamètre","difficulty":"difficulté","dirty":"sale","dull":"terne","duty":"devoir","eager":"désireux","eleven":"Onze","engineer":"ingénieur","equally":"également","equator":"équateur","fierce":"féroce","firm":"raffermir","fix":"réparer","flame":"flamme","former":"ancien","forty":"quarante","fox":"Renard","Fred":"Fred","frog":"la grenouille","fully":"pleinement","goose":"OIE","gravity":"la gravité","Greece":"Grèce","guard":"garde","gulf":"golfe","handsome":"Beau","harbor":"port","hay":"foins","hello":"Bonjour","horn":"klaxon","hospital":"hôpital","ill":"mauvais","interior":"intérieur","Jeff":"Jeff","jungle":"jungle","labor":"la main d'oeuvre","limited":"limité","location":"emplacement","mainly":"principalement","managed":"géré","Maria":"Maria","mental":"mental","mixture":"mélange","movie":"film","nearer":"plus près","nervous":"nerveux","noted":"c'est noté","October":"octobre","officer":"officier","Ohio":"Ohio","opinion":"opinion","opportunity":"opportunité","organization":"organisation","package":"paquet","pale":"pâle","plastic":"Plastique","Pole":"Pôle","port":"Port","pour":"verser","private":"privé","properly":"correctement","protection":"protection","pupil":"élève","rear":"arrière","refused":"refusé","roar":"rugir","Rome":"Rome","Russia":"Russie","Russian":"russe","saddle":"selle","settle":"régler","shelf":"étagère","shelter":"abri","shine":"éclat","sink":"évier","slabs":"dalles","slave":"esclave","somehow":"en quelque sorte","split":"Divisé","stems":"tiges","stock":"Stock","swept":"balayé","thy":"tes","tide":"marée","torn":"déchiré","troops":"troupes","tropical":"tropical","typical":"typique","unhappy":"malheureux","vertical":"verticale","victory":"la victoire","voyage":"voyage","welcome":"Bienvenue","weren't":"n'étaient pas","whistle":"sifflet","widely":"largement","worried":"préoccupé","wrapped":"enveloppé","writer":"écrivain"},
	        {"acres":"des acres","adult":"adulte","advice":"Conseil","arrangement":"arrangement","attempt":"tentative","August":"août","Autumn":"L'automne","border":"frontière","breeze":"brise","brick":"brique","calm":"calme","canal":"canal","Casey":"Casey","cast":"jeter","chose":"choisi","claws":"les griffes","coach":"entraîneur","constantly":"constamment","contrast":"contraste","cookies":"biscuits","customs":"douane","damage":"dommage","Danny":"Danny","deeply":"profondément","depth":"profondeur","discussion":"discussion","doll":"poupée","donkey":"âne","Egypt":"Egypte","Ellen":"Ellen","essential":"essentiel","exchange":"échange","exist":"exister","explanation":"explication","facing":"orienté vers","film":"film","finest":"le plus beau","fireplace":"cheminée","floating":"flottant","folks":"gens","fort":"fort","garage":"garage","grabbed":"saisi","grandmother":"grand-mère","habit":"habitude","happily":"Heureusement","Harry":"Harry","heading":"titre","hunter":"chasseur","Illinois":"Illinois","image":"image","independent":"indépendant","instant":"instant","January":"janvier","kids":"des gamins","label":"étiquette","Lee":"Lee","lungs":"poumons","manufacturing":"fabrication","Martin":"Martin","mathematics":"mathématiques","melted":"fondu","memory":"Mémoire","mill":"moulin","mission":"mission","monkey":"singe","Mount":"Monter","mysterious":"mystérieux","neighborhood":"quartier","Norway":"Norvège","nuts":"des noisettes","occasionally":"parfois","official":"officiel","ourselves":"nous-mêmes","palace":"palais","Pennsylvania":"Pennsylvanie","Philadelphia":"crême Philadelphia","plates":"assiettes","poetry":"poésie","policeman":"policier","positive":"positif","possibly":"peut-être","practical":"pratique","pride":"fierté","promised":"promis","recall":"rappel","relationship":"relation","remarkable":"remarquable","require":"exiger","rhyme":"rime","rocky":"rocheux","rubbed":"frotté","rush":"se ruer","sale":"vente","satellites":"satellites","satisfied":"satisfait","scared":"effrayé","selection":"sélection","shake":"secouer","shaking":"tremblement","shallow":"peu profond","shout":"crier","silly":"idiot","simplest":"le plus simple","slight":"légère","slip":"caleçon","slope":"pente","soap":"savon","solar":"solaire","species":"espèce","spin":"tourner","stiff":"rigide","swung":"balancé","tales":"contes","thumb":"pouce","tobacco":"le tabac","toy":"jouet","trap":"piège","treated":"traité","tune":"régler","University":"Université","vapor":"vapeur","vessels":"navires","wealth":"richesse","wolf":"Loup","zoo":"zoo"}
	      ];
  function getUrlVars() {
    var vars = {};
    var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
      vars[key] = value;
    });
    return vars;
  }

  function htmlDecode(str){
    return str
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&amp;/g, '&');
  }
  function getUrlParam(parameter, defaultvalue){
      var urlparameter = defaultvalue;
      if(window.location.href.indexOf(parameter) > -1){
          urlparameter = getUrlVars()[parameter];
          }
      return urlparameter;
  }
  function translate_entry(entry) {
    return entry.split(/\\s+/).map(
        word => {
          let res_word;
          if (current_dictionary[word]) {
            res_word = "<span style='color:red;'>"+current_dictionary[word]+'</span>'
          } else {
            res_word = word
          }
          // res_word"<span style='color:red;'>"+simple_words[word]+'</span>' || word //"_".repeat(word.length)
          return res_word;
        }
      ).join(" ");
  }

  var subtitle_template_url = "https://video.google.com/timedtext?lang=en&v=",
      video_id = getUrlParam('v','XdAyvrFvEzs'),
      movie_player = document.getElementById("movie_player"),
      current_knowledge_level = parseInt( localStorage['lazy_land__knowledge_level'] || getUrlParam('level',"10") ),
      current_dictionary = Object.assign({}, ...simple_words.slice(0,current_knowledge_level)),
      div_subtitles, div_translated_subtitles, inst,
      xml_data = [],xml_current_entry = -1,
      loop_inst = null,
      previousPlayerState = -100; // just a random number

  function get_subtitles(video_id, my_callback) {
    let subtitle_url = subtitle_template_url + video_id;
    var xhr = new XMLHttpRequest();
    xhr.open('GET', subtitle_url);
    xhr.onload = function() {
        if (xhr.status === 200) {
        	//console.log("FAQ ");
        	//console.log(subtitle_url);
            let parser = new DOMParser();
            let xml = parser.parseFromString(xhr.responseText,"text/xml");
            let xml_texts = xml.children[0].children;
            // let txts = [];
            // for (let i = 0; i < xml_texts.length; i++) {
            // 	txts.push(htmlDecode(xml_texts[i].innerHTML));
            // }
            // get_translate_from_server(txts, function () {

            // });
			//console.log(xml_texts);
            for (let i = 0; i < xml_texts.length; i++) {
              let txt = xml_texts[ i ];
              let decodedText = htmlDecode(txt.innerHTML)
              xml_data.push({
                  start: parseFloat(txt.getAttribute("start")),
                  dur: parseFloat(txt.getAttribute("dur")),
                  text: decodedText,
                  translate_text: translate_entry( decodedText )
                });
            }
            my_callback();
        }
        else {
            alert('Request failed.  Returned status of ' + xhr.status);
        }
    };
    xhr.send();
  }

  function getCurrentTime() {
    return movie_player.getCurrentTime();
  }
  var parentElement,firstOne,
      drawn = false;
  function loopFunction() {
    let event_data = movie_player.getPlayerState();
    //console.log(event_data);
    // quit in case the same thing is happening
    if (event_data == previousPlayerState) return;
    if (event_data == 0) { // ENDED
      clearInterval(inst);
      changeTimeField();
      div_subtitles.innerHTML = "";
      div_translated_subtitles.innerHTML = "";
    } else if (event_data == 1) { // PLAYING
        changeTimeField();
        inst = setInterval(changeTimeField, 100);  
        previousPlayerState = event_data;
    } else if (inst && event_data == 2 ){ // PAUSED
      clearInterval(inst);
      changeTimeField();
      previousPlayerState = event_data
    } else  {
      previousPlayerState = event_data
    }
  }

  function changeTimeField() {
        let timestamp = movie_player.getCurrentTime();
        let initial_value;

        if ( xml_current_entry < 0 || xml_data[xml_current_entry]["start"] > timestamp) {
          initial_value = 0;
        } else if (xml_data[xml_current_entry]["start"] <= timestamp &&
                    xml_data[xml_current_entry+1]["start"] >= timestamp) {
          return;
        } else {
          initial_value = xml_current_entry + 1;
        }
		//console.log(xml_data.length-1);
        for (let i = initial_value; i < xml_data.length-1; i++ ) {
          if (xml_data[i]["start"] <= timestamp &&
              xml_data[i+1]["start"] >= timestamp) {
            xml_current_entry = i;
	        div_subtitles.innerHTML = xml_data[xml_current_entry]["text"];
	        div_translated_subtitles.innerHTML = xml_data[xml_current_entry]["translate_text"];
	        //console.log("HAHAHAHAH");

            break;
          }
        }
      }

  function wait_function(cb1) {
      parentElement = document.getElementById('info-contents');
      if (parentElement && parentElement.childElementCount > 0) {
      	  firstOne = parentElement.firstChild;
          div_subtitles = document.createElement('div');
          div_subtitles.setAttribute('id', 'subtitles');
          div_subtitles.setAttribute('class', 'my_subtitles');
          // div_subtitles.innerHTML = "FASFHASsdljghaejlghasljghasldjhgsdaljhvb";
          div_translated_subtitles = document.createElement('div');
          div_translated_subtitles.setAttribute('id', 'translated_subtitles');
          div_translated_subtitles.setAttribute('style', 'font-size:250%');
          div_translated_subtitles.setAttribute('class', 'my_subtitles_translation');
          // div_translated_subtitles.innerHTML = "FASFHAS:UFHASIUFHASIFU";
          parentElement.insertBefore(div_subtitles, firstOne);
          parentElement.insertBefore(div_translated_subtitles, firstOne); 
          cb1();
      } else {
      	setTimeout(function() {
      		  wait_function(cb1);
              // wait_function(cb0, cb1);
          }, 200);
      }
  }

  function get_translate_from_server(list, callback) {
  	let str_parameters = JSON.stringify(list);
  	escape(str_parameters);
	//console.log("https://846006a2.ngrok.io/query-youtube?text=" + str_parameters)
	// var xhr = new XMLHttpRequest();

	// xhr.open("GET", "https://846006a2.ngrok.io/query-youtube?text=" + str_parameters, true);

	// //Send the proper header information along with the request
	// xhr.setRequestHeader("Content-type", "application/json");

	// xhr.onreadystatechange = function() {
	// 	//console.log(xhr.readyState);
	// 	//console.log(xhr.responseText);
	//   if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200) {
	//     callback();
	//   }
	// };
	// xhr.send();
  }

  window.onload = function() {
  	get_subtitles(video_id, function() {
	    wait_function(function() {
	    	loopFunction();
	    	loop_inst = setInterval(loopFunction, 100);	
	    });
	  });
  }
  `;
  var codeElement = document.createTextNode(code);
  script.appendChild(codeElement);
  document.querySelector("head").appendChild(script);

}